---

# Add odldev user in ODLDEV group and grant sudo permission
- group: name=ODLDEV
- user: name=odldev comment="ODL developer" uid=1010 group="ODLDEV" groups="wheel" shell=/bin/bash password=$6$rounds=656000$lL0xQ0LBywL04CXY$D4GxCJGv4P/dSpRkNJgUB/VB9XnXR94sOE9JTMuK189FrVhLbesixzhU0qfjuN3NihdH7YOs0RtsrhtEOGNey0

- name: Initialise .xinirtc for RedHat Gnome Shell desktop
  shell: echo "exec gnome-session" >> ~odldev/.xinitrc
  when: redhat_desktop == 'gnome_shell'

- name: Initialise .xinirtc for RedHat KDE desktop
  shell: echo "exec startkde" >> ~odldev/.xinitrc
  when: redhat_desktop == 'kde'

- name: Initialise .xinirtc for RedHat Cinnamon desktop
  shell: echo "exec /usr/bin/cinnamon-session" >> ~odldev/.xinitrc
  when: redhat_desktop == 'cinnamon'

- name: Initialise .xinirtc for RedHat MATE desktop
  shell: echo "exec /usr/bin/mate-session" >> ~odldev/.xinitrc
  when: redhat_desktop == 'mate'

- name: Initialise .xinirtc for RedHat Xfce desktop
  shell: echo "exec /usr/bin/xfce4-session" >> ~odldev/.xinitrc
  when: redhat_desktop == 'xfce'

- name: Set ownership for RedHat desktop .xinitrc
  file: path=~odldev/.xinitrc owner=odldev group=ODLDEV mode=0644 state=touch
  when: ansible_os_family == 'RedHat' and redhat_desktop != 'gnome'
